"""Paper-only portfolio and scheduling constants from the approved spec."""
PAPER_EQUITY_USDT = 10_000
CORE_SIZE = 5
BENCH_SIZE = 5
PROMOTION_MARGIN = 10
CORE_MIN_HOLD_HOURS = 2
MAX_SWAPS_PER_SCAN = 1
MAX_BOTS = CORE_SIZE
NOTIONAL_PER_BOT_USDT = 1_000
SLOTS = {'NEUTRAL': 2, 'LONG': 2, 'SHORT': 2}
DIRECTION_CAP = 4
LEVERAGE_TREND = 5
LEVERAGE_NEUTRAL = 5
STEP_NEUTRAL_PCT = .45
RESERVE_PER_BOT_USDT = 200
NEUTRAL_RESERVE_USDT = RESERVE_PER_BOT_USDT
MAJORS_MAX = 1
MOVERS_MAX = 1
MAJORS = ('XBTUSDTM', 'ETHUSDTM', 'SOLUSDTM')
MIN_EXPECTED_GRIDS_PER_HOUR = 2.0
COOLDOWN_HOURS = 6
MAX_AGE_HOURS = 72
TICK_INTERVAL_S = 10
DECISION_INTERVAL_S = 300
SNAPSHOT_MAX_INTERVAL_S = 30
TICK_STALE_ALERT_S = 180
KUCOIN_DOWN_ALERT_S = 300
# System ERROR event codes (type ERROR, bot_id 0, symbol SYSTEM) in events.jsonl.
LOCAL_ERROR = 5  # policy/engine failure after a successful transport pass;
                 # kucoin_ok stays unchanged and the tick continues.
